var navs = [{
	"title": "后台首页",
	"icon": "fa-home",
	"href": "https://www.baidu.com",
	"spread": false,
	"selected": true 
	}, {
	"title": "系统设置",
	"icon": "fa-cubes",
	"spread": false,
	"children": [{
		"title": "按钮",
		"href": "https://www.2345.com"
	}, {
		"title": "树形列表",
		"href": "sys/menu"
	}, {
		"title": "表格",
		"href": "table.html"
	}, {
		"title": "导航",
		"href": "nav.html"
	}, {
		"title": "Tab选项卡",
		"href": "tab.html"
	}, {
		"title": "菜单管理",
		"href": "auxiliar.html"
	}]
}, {
	"title": "组件",
	"icon": "fa-cogs",
	"spread": false,
	"children": [{
		"title": "Datatable",
		"icon": "fa-table",
		"href": "begtable.html"
	}, {
		"title": "Navbar组件",
		"icon": "fa-navicon",
		"href": "navbar.html"
	}, {
		"title": "Laytpl+Laypage",
		"icon": "&#xe628;",
		"href": "paging.html"
	}]
}, {
	"title": "地址本",
	"icon": "fa-address-book",
	"href": "",
	"spread": false,
	"children": [{
		"title": "Github",
		"icon": "fa-github",
		"href": "https://www.github.com/"
	}, {
		"title": "QQ",
		"icon": "fa-qq",
		"href": "http://www.qq.com/"
	}, {
		"title": "Fly社区",
		"icon": "&#xe609;",
		"href": "http://fly.layui.com/"
	}, {
		"title": "新浪微博",
		"icon": "fa-weibo",
		"href": "http://weibo.com/"
	}]
}, {
	"title": "这是一级导航",
	"icon": "fa-stop-circle",
	"href": "https://www.baidu.com",
	"spread": false
}];